
--  等级 = {l1,l2,l3,l4,l5,l6,l7}
local l1 = { 60, 20, 10, 05, 05, 00, 00 }
local l2 = { 30, 50, 10, 05, 05, 00, 00 }
local l3 = { 10, 25, 40, 15, 05, 05, 00 }
local l4 = { 05, 10, 25, 40, 15, 05, 05 }
local l5 = { 00, 05, 10, 25, 40, 15, 05 }
local l6 = { 00, 00, 05, 10, 25, 40, 15 }
local l7 = { 00, 00, 00, 05, 15, 25, 45 }

DROPPABLE_ABILITY_DEFINATION = {
	item_antimage_mana_break = l1,
    item_axe_berserkers_call = l1,
    item_axe_counter_helix = l2,
    item_drow_ranger_trueshot = l3,
    item_drow_ranger_marksmanship = l3,
    item_earthshaker_enchant_totem = l3,
    item_earthshaker_aftershock = l3,
    item_earthshaker_echo_slam = l7,
    item_juggernaut_blade_dance = l4,
    item_juggernaut_blade_fury = l4,
    item_kunkka_tidebringer = l4,
    item_lina_fiery_soul = l2,
    item_mirana_leap = l2,
    item_mirana_starfall = l4,
    item_nevermore_shadowraze1 = l1,
    item_nevermore_shadowraze2 = l1,
    item_nevermore_shadowraze3 = l1,
    item_nevermore_necromastery = l6,
    item_nevermore_dark_lord = l5,
    item_nevermore_requiem = l6,
    item_puck_waning_rift = l2,
    item_puck_phase_shift = l2,
    item_pudge_rot = l5,
    item_razor_plasma_field = l3,
    item_razor_eye_of_the_storm = l6,
    item_skeleton_king_mortal_strike = l3,
    item_death_prophet_exorcism = l6,
    item_sven_great_cleave = l3,
    item_sven_warcry = l1,
    item_sven_gods_strength = l4,
    item_storm_spirit_static_remnant = l4,
    item_storm_spirit_overload = l1,
    item_sandking_caustic_finale = l3,
    item_sandking_epicenter = l5,
    item_tiny_craggy_exterior = l2,
    item_tiny_grow = l5,
    item_zuus_static_field = l1,
    item_slardar_sprint = l2,
    item_slardar_slithereen_crush = l4,
    item_slardar_bash = l3,
    item_tidehunter_kraken_shell = l2,
    item_tidehunter_anchor_smash = l3,
    item_tidehunter_ravage = l5,
    item_vengefulspirit_command_aura = l2,
    item_crystal_maiden_brilliance_aura = l1,
    item_crystal_maiden_freezing_field = l4,
    item_windrunner_windrun = l3,
    item_windrunner_focusfire = l5,
    item_sniper_headshot = l1,
    item_sniper_take_aim = l1,
    item_necrolyte_death_pulse = l3,
    item_necrolyte_heartstopper_aura = l1,
    item_beastmaster_inner_beast = l2,
    item_queenofpain_scream_of_pain = l4,
    item_venomancer_poison_sting = l1,
    item_venomancer_poison_nova = l3,
    item_phantom_assassin_blur = l1,
    item_phantom_assassin_coup_de_grace = l3,
    item_templar_assassin_refraction = l3,
    item_viper_nethertoxin = l2,
    item_viper_corrosive_skin = l3,
    item_luna_lunar_blessing = l2,
    item_dragon_knight_dragon_blood = l3,
    item_dragon_knight_frost_breath = l4,
    item_leshrac_diabolic_edict = l5,
    item_leshrac_pulse_nova = l6,
    item_life_stealer_rage = l2,
    item_clinkz_strafe = l3,
    item_clinkz_searing_arrows = l3,
    item_omniknight_degen_aura = l1,
    item_omniknight_guardian_angel = l4,
    item_enchantress_untouchable = l3,
    item_huskar_burning_spear = l1,
    item_huskar_berserkers_blood = l1,
    item_broodmother_poison_sting = l1,
    item_broodmother_incapacitating_bite = l1,
    item_broodmother_insatiable_hunger = l3,
    item_bounty_hunter_jinada = l2,
    item_weaver_time_lapse = l3,
    item_jakiro_liquid_fire = l2,
    item_spectre_desolate = l1,
    item_spectre_dispersion = l1,
    item_doom_bringer_scorched_earth = l2,
    item_spirit_breaker_greater_bash = l2,
    item_ursa_earthshock = l3,
    item_ursa_overpower = l5,
    item_ursa_fury_swipes = l2,
    item_ursa_enrage = l5,
    item_silencer_glaives_of_wisdom = l1,
    item_obsidian_destroyer_arcane_orb = l1,
    item_obsidian_destroyer_essence_aura = l1,
    item_lycan_howl = l1,
    item_lone_druid_savage_roar = l1,
    item_lone_druid_true_form_battle_cry = l1,
    item_brewmaster_thunder_clap = l1,
    item_meepo_geostrike = l2,
    item_rubick_null_field = l1,
    item_nyx_assassin_spiked_carapace = l1,
    item_naga_siren_rip_tide = l3,
    item_visage_gravekeepers_cloak = l2,
    item_slark_pounce = l5,
    item_troll_warlord_battle_trance = l5,
    item_centaur_hoof_stomp = l2,
    item_centaur_return = l1,
    item_centaur_stampede = l5,
    item_magnataur_reverse_polarity = l5,
    item_bristleback_quill_spray = l3,
    item_bristleback_bristleback = l1,
    item_bristleback_warpath = l4,
    item_abaddon_frostmourne = l2,
    item_ember_spirit_flame_guard = l5,
}

function GetRandomDropAbility()
	local level = GameRules.gamemode:GetCurrentLevel()
    local randomTable = {{item = nil, Weight = 0}}
    for itemname, dropTable in pairs(DROPPABLE_ABILITY_DEFINATION) do
        table.insert(randomTable, {
            item = itemname,
            Weight = dropTable[level]
        })
    end

    return table.random_with_weight(randomTable).item
end