LinkLuaModifier("modifier_attribute_fix", "modifiers/generic/modifier_attribute_fix", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_movespeed_no_limit", "modifiers/generic/modifier_movespeed_no_limit.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_no_unit_collision", "modifiers/generic/modifier_no_unit_collision.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_no_healthbar", "modifiers/generic/modifier_no_healthbar.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_unselectable", "modifiers/creatures/modifier_unselectable.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_ignore_cast_angle", "modifiers/generic/modifier_ignore_cast_angle.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_generic_invunerable", "modifiers/generic/modifier_generic_invunerable.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_invunerable_after_damage", "modifiers/generic/modifier_player_invunerable_after_damage.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_attack_range", "modifiers/generic/modifier_attack_range.lua", LUA_MODIFIER_MOTION_BOTH)
LinkLuaModifier("modifier_ed_continous_damage", "modifiers/generic/modifier_ed_continous_damage.lua", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_creature_bullet_thinker", "modifiers/creatures/modifier_creature_bullet_thinker", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_creature_pudge_hate", "modifiers/creatures/boss_pudge/modifier_creature_pudge_hate.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_touch_damage", "modifiers/creatures/modifier_touch_damage.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_disarmed", "modifiers/creatures/modifier_disarmed.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_creature_invulnerable", "modifiers/creatures/modifier_creature_invulnerable.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_melee_unit_movespeed_burster","modifiers/creatures/modifier_melee_unit_movespeed_burster.lua",LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_ed_prop", "modifiers/props/modifier_ed_prop.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_creature_damage_tracker", "modifiers/creatures/modifier_creature_damage_tracker.lua", LUA_MODIFIER_MOTION_NONE) -- 还没做
LinkLuaModifier("modifier_creature_leap", "modifiers/creatures/modifier_creature_leap.lua", LUA_MODIFIER_MOTION_BOTH)
LinkLuaModifier("modifier_creature_knockback", "modifiers/creatures/modifier_creature_knockback.lua", LUA_MODIFIER_MOTION_BOTH)

LinkLuaModifier("modifier_player_entering_next_level", "modifiers/characters/modifier_player_entering_next_level.lua", LUA_MODIFIER_MOTION_HORIZONTAL)
